# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

##############################################################################code which may help
# def on_set_button_clicked(self, set_id):
#     sets_file = "sets.json"
#
#     with open(sets_file, "r") as f:
#         sets = json.load(f)
#
#     for set_data in sets:
#         if set_data["id"] == set_id:
#             print(set_data)
#             break
#
#
# def load_sets_data(self):
#     sets_file_path = "sets.json"
#
#     if not os.path.exists(sets_file_path):
#         with open(sets_file_path, "w") as f:
#             f.write('{"Sets": []}')
#
#     with open(sets_file_path, "r") as f:
#         sets_data = json.load(f)
#
#     return sets_data["Sets"]
#
#
# def save_sets_data(self):
#     sets_file_path = "sets.json"
#     sets_data = {"Sets": self.sets_data}
#
#     with open(sets_file_path, "w") as f:
#         json.dump(sets_data, f, indent=4)
#
#
# def on_set_label_click(self, set_id):
#     for set_data in self.sets_data:
#         if set_data["id"] == set_id:
#             print(set_data)
#             break
#
#
# def on_add_set_button_click(self):
#     new_set_name = "New Set"
#     new_set_fields = []
#
#     new_set_data = {
#         "id": len(self.sets_data) + 1,
#         "name": new_set_name,
#         "fields_to_load": new_set_fields
#     }
#
#     self.sets_data.append(new_set_data)
#
#     new_set_label = QLabel(new_set_name, self.sets_container)
#     new_set_label.mousePressEvent = lambda event, set_id=new_set_data["id"]: self.on_set_label_click(set_id)
#
#     self.layout.addWidget(new_set_label)
#
#     self.save_sets_data()



from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.scrollArea = QtWidgets.QScrollArea(Form) # 1
        self.scrollArea.setGeometry(QtCore.QRect(40, 40, 291, 221)) # 2
        self.scrollArea.setWidgetResizable(True) # 3
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget() # 4
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 289, 219)) # 5
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.formLayout = QtWidgets.QFormLayout(self.scrollAreaWidgetContents)
        self.formLayout.setObjectName("formLayout")
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pushButton)
        self.lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lineEdit)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "PushButton"))
